const skills = [
  {
    name: "React",
    icon: "react",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#62DAFB",
    type: "fab",
  },
  {
    name: "Angular",
    icon: "angular",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#de0031",
    type: "fab",
  },
  {
    name: "Javascript",
    icon: "js-square",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#f7e01b",
    type: "fab",
  },
  {
    name: "Wordpress",
    icon: "wordpress",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#207195",
    type: "fab",
  },
  {
    name: "Html",
    icon: "html5",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#f16629",
    type: "fab",
  },
  {
    name: "PHP",
    icon: "php",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#7478ae",
    type: "fab",
  },
  ,
  {
    name: "Node.JS",
    icon: "node-js",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#5b8556",
    type: "fab",
  },
  ,
  {
    name: "NPM",
    icon: "npm",
    fontSize: "48px",
    progress: 90,
    value: 100,
    color: "#C53635",
    type: "fab",
  },
  ,
  {
    name: "Mongo DB",
    icon: "database",
    fontSize: "48px",
    progress: 90,
    value: 100,
    type: "fas",
    color: "#6AB23F",
  },

  //ADD MORE HERE
];

export default skills;
